name: style_hub
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  meta: ^1.11.0
  flutter_bloc: ^8.1.5
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.1
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.0
  either_dart: ^1.0.0
  get_it: ^7.6.9
  shimmer: ^3.0.0
  google_maps_flutter: ^2.6.1
  flutter_otp_text_field: ^1.1.3+2
  persistent_bottom_nav_bar:
    git:
      url: https://github.com/duressa-feyissa/PersistentBottomNavBar.git
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/static/Mulish-Black.ttf
        - asset: assets/fonts/Mulish/static/Mulish-BlackItalic.ttf
        - asset: assets/fonts/Mulish/static/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish/static/Mulish-BoldItalic.ttf
        - asset: assets/fonts/Mulish/static/Mulish-ExtraBold.ttf
        - asset: assets/fonts/Mulish/static/Mulish-ExtraBoldItalic.ttf
        - asset: assets/fonts/Mulish/static/Mulish-ExtraLight.ttf
        - asset: assets/fonts/Mulish/static/Mulish-ExtraLightItalic.ttf
        - asset: assets/fonts/Mulish/static/Mulish-Italic.ttf
        - asset: assets/fonts/Mulish/static/Mulish-Light.ttf
        - asset: assets/fonts/Mulish/static/Mulish-LightItalic.ttf
        - asset: assets/fonts/Mulish/static/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish/static/Mulish-MediumItalic.ttf
        - asset: assets/fonts/Mulish/static/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish/static/Mulish-SemiBold.ttf
        - asset: assets/fonts/Mulish/static/Mulish-SemiBoldItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Mulish/Mulish-VariableFont_wght.ttf

  assets:
    - assets/icons/notifaction.svg
    - assets/images/onboarding/1.png
    - assets/images/onboarding/2.png
    - assets/images/onboarding/3.png
